name: PR AI Scanner

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create env file from PR_SCANNER secret
        run: |
          # Decode the base64-encoded PR_SCANNER secret into a file for Docker to use
          echo "${{ secrets.PR_SCANNER }}" | base64 --decode > pr_scanner.env

      - name: Run PR Scanner
        id: pr_scanner
        run: |
          docker run \
              --env-file pr_scanner.env \
              -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
              -e GITHUB_REPOSITORY="${{ github.repository }}" \
              -e GITHUB_ISSUE_NUMBER="${{ github.event.number }}" \
              -e PROJECT_ROOT=/src \
              -v "/tmp/out:/out" \
              -v "$(pwd):/src" \
              nady5730642/ai-scan-job:latest
