name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Run PR Scanner
        id: pr_scanner
        run: |
          OUTPUT=$(docker run hello-world)
          echo "docker_output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Delete existing bot comment if any
        uses: actions/github-script@v6
        env:
          DOCKER_OUTPUT: ${{ steps.run_docker.outputs.docker_output }}
        with:
          script: |
            // List all comments on the pull request
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            // Find a comment containing the unique marker
            const botComment = comments.find(comment => comment.body.includes('<!-- my-bot-comment -->'));
            if (botComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
      - name: Create new bot comment with timestamp
        uses: actions/github-script@v6
        with:
          script: |
            // Get current timestamp
            const timestamp = new Date().toISOString();
            // Build the new comment message with unique marker and timestamp
            const message = `<!-- my-bot-comment --> A new commit has been pushed to this pull request. Timestamp: ${timestamp} 

            OUTPUT: 
            ${process.env.DOCKER_OUTPUT}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message,
            });