name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  issues: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for your pull request! We will review it shortly."
            })